### ISSUE TITLE
Potentially missing data

### ISSUE THREAD

**Issue by matthew-law** [alasdairrae/yum#1]
This looks really interesting …but is the actual data missing? I can only see the README.md and LICENSE files in the repo, not any .csv file :(

**Comment by alasdairrae** [comment]
Ah, thanks a lot for pointing this out. I think this might be a repo I started, forgot about and then put the files somewhere else - as in this blog post, which links to the csvs


http://www.statsmapsnpix.com/2021/10/food-for-thought.html

**Comment by matthew-law** [comment]
Perfect, thank you!
